exp_name: 'parse_mft_check_same_values'
data_path: 
dfxml_path: '/content/drive/MyDrive/security_mft/dfxml_files/temp.dfxml'
output_path: '/content/drive/MyDrive/security_mft/output/'  
mode:  'run' #run or test